### ISSUE TITLE
Generate a table in Ocaml

### ISSUE THREAD

**Issue by tobiasBora** [ocsigen/macaque#34]
Hello !

I would like to know, is it possible to generate in ocaml a Macaque table ? Because I am building a library that is supposed to add/remove columns in a table in order to fit a table model, and after that I would love to be able to generate the macaque table.

I would like for example use a type that can describe a table, create such a table description (let's call it A), then give A to a "correct" function that edit the table in the database in order to have the same schema as in A, and finally create a macaque table B that fits A. Of course I could write by hand B in macaque language, and A in my own type, but I don't wan't that the user type two description of the database. If it's not possible I will do a script that autogenerate the macaque .ml code from the A type, but if I could avoid such a dirty trick it would be great.

Thank you in advance,

TobiasBora.

**Comment by gasche** [comment]
Hi,

I'm terribly busy (full-day seminars with no internet access) right now.
Please ping me back if I haven't answered your mail by next week, but right
now I think a very quick answer would be "no it's not possible right away"
(Macaque relies by design on static typing, and OCaml is not able to
express change of type during interaction). But maybe I can say more when I
have more time to think about it.

Sorry

**Comment by tobiasBora** [comment]
Hello,

Thank you for your answer ! And don't worry, it's not urgent. So if I understand well the only way to do that would be to write a pretty hard to code ppx extension ? Then I think I'm going to write a script that convert a global table type into a .ml file with the good macaque type.

**Comment by gasche** [comment]
Meta-programming is certainly an option.

What you cannot do is the following: provide, in the same program, the
option to dynamically change the table layout, and static OCaml code that
access the table layout in a strongly-typed way, with full typing
information of the current state of the table (because the static type of
the table is not a well-defined concept if it evolves over time).

With enough effort, we could devise a GADT representation of the stable
structure that would allow both dynamic evolution of the structure, and the
manipulation of well-typed operations on the structure. But those
operations would have to be generic over the structure (a function that
takes the table structure and decides which operation to offer), and they
would not use the Macaque syntax. Doing this kind of things without trying
to type-check them statically is easier.

Note that it should be sound to describe in Macaque only a subset of the
columns of a table. So if your table has both dynamic columns that you
expect to evolve over time through schema-administration actions, and a set
of static columns that will evolve much more rarely, you could describe
only the static columns to Macaque and benefit from type-safety for
operations that are restricted to this part.

**Comment by tobiasBora** [comment]
Thank you for your answer, and sorry for the time I made to answer, I didn't see it before today.

I understand that it's not possible (or quite hard, I'm not very familiar with GADTs) to edit a database structure and keep a safe type checking. But is it possible to do non-safe operations with macaque or do I need to use the unsafe PGOcaml alter function to deal with a database whose structure isn't constant ?

And here is maybe a more simple thing to do: is it possible to get the structure of a Macaque database to manually check that the database fit the macaque structure (and eventually correct it if necessary) ?

**Comment by gasche** [comment]
The Check module already does that for you (at runtime, by using pgsql
inspection functions). I could actually add a function to the API that
returns a user-manipulable version of the table. Would you create an issue
on https://github.com/ocsigen/macaque if that's what you need?

**Comment by tobiasBora** [comment]
A function that returns a user-manipulable version of the table could be
quite usefull actually... The only problem of that is that it is not
possible to give lot's of informations on a column (what size ?...),
that's why I choose an other way to solve my problem (I generate the
Ocaml code from a more general code), but if it's pretty easy to do it
could be usefull.

I will create this issue right now.

Thank you for your help and work !

TobiasBora.
